/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Wordle API
 * This is an API for Wordle
 * OpenAPI spec version: 1.1.1
 */
export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface HealthResponse {
  status: string;
  response: string;
}

export interface PingResponse {
  response: string;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export interface WordleSolveRequest {
  words: string[];
  places: string[];
  size: number;
}

export interface WordleSolveResponse {
  suggestions: string[];
  alternatives: string[];
  remaining: number;
  used_letters: string[];
}
