/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Wordle API
 * This is an API for Wordle
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import { unref } from "vue";
import type { MaybeRef } from "vue";
import type { WordleSolveRequest, WordleSolveResponse } from "./wordleAPI.schemas";

/**
 * @summary Solve Wordle
 */
export const fwordlesolverApiApiSolveWordle = (
  wordleSolveRequest: MaybeRef<WordleSolveRequest>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<WordleSolveResponse>> => {
  wordleSolveRequest = unref(wordleSolveRequest);

  return axios.default.post(`/wordle-solver/api/wordle`, wordleSolveRequest, options);
};

export const getFwordlesolverApiApiSolveWordleMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof fwordlesolverApiApiSolveWordle>>,
    TError,
    { data: WordleSolveRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof fwordlesolverApiApiSolveWordle>>,
  TError,
  { data: WordleSolveRequest },
  TContext
> => {
  const mutationKey = ["fwordlesolverApiApiSolveWordle"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof fwordlesolverApiApiSolveWordle>>,
    { data: WordleSolveRequest }
  > = (props) => {
    const { data } = props ?? {};

    return fwordlesolverApiApiSolveWordle(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FwordlesolverApiApiSolveWordleMutationResult = NonNullable<
  Awaited<ReturnType<typeof fwordlesolverApiApiSolveWordle>>
>;
export type FwordlesolverApiApiSolveWordleMutationBody = WordleSolveRequest;
export type FwordlesolverApiApiSolveWordleMutationError = AxiosError<unknown>;

/**
 * @summary Solve Wordle
 */
export const useFwordlesolverApiApiSolveWordle = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof fwordlesolverApiApiSolveWordle>>,
    TError,
    { data: WordleSolveRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof fwordlesolverApiApiSolveWordle>>,
  TError,
  { data: WordleSolveRequest },
  TContext
> => {
  const mutationOptions = getFwordlesolverApiApiSolveWordleMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Ping
 */
export const fwordlesolverApiApiPing = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.get(`/wordle-solver/api/ping`, options);
};

export const getFwordlesolverApiApiPingQueryKey = () => {
  return ["wordle-solver", "api", "ping"] as const;
};

export const getFwordlesolverApiApiPingQueryOptions = <
  TData = Awaited<ReturnType<typeof fwordlesolverApiApiPing>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof fwordlesolverApiApiPing>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = getFwordlesolverApiApiPingQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof fwordlesolverApiApiPing>>> = ({
    signal,
  }) => fwordlesolverApiApiPing({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof fwordlesolverApiApiPing>>,
    TError,
    TData
  >;
};

export type FwordlesolverApiApiPingQueryResult = NonNullable<
  Awaited<ReturnType<typeof fwordlesolverApiApiPing>>
>;
export type FwordlesolverApiApiPingQueryError = AxiosError<unknown>;

/**
 * @summary Ping
 */

export function useFwordlesolverApiApiPing<
  TData = Awaited<ReturnType<typeof fwordlesolverApiApiPing>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof fwordlesolverApiApiPing>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFwordlesolverApiApiPingQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}
