name: 📦 Build Package Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  build-release:
    # trigger only if bot is not the author of the commit
    if: ${{ github.event.head_commit.author.username != 'github-actions[bot]' }}
    name: Build Package Release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python
