name: 📦 Build Package Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  build_release:
    name: Build Package Release
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs.release }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
  docker_release:
    needs: build_release
    # if: needs.build_release.outputs.release.releases_created
    # uses: ./.github/workflows/publish.yml
    # with:
    #   tag_name: ${{ needs.build_release.outputs.release.tag_name }}
    # secrets: inherit
    runs-on: ubuntu-latest
    steps:
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump needs context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: echo "$NEEDS_CONTEXT"
