name: 📦 Build Package Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  build_release:
    name: Build Package Release
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs.release }}
    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python
  docker_release:
    needs: build_release
    if: needs.build_release.outputs.release.releases_created
    uses: ./.github/workflows/publish.yml
    with:
      tag_name: ${{ needs.build_release.outputs.release.tag_name }}
    secrets: inherit
